Add new environment with latest versions
Note:
If "setuptools" is set to the latest version, I get an error with Atlite:
ModuleNotFoundError: No module named ‘pkg_resources'.

Apparently, “setuptools", from version 82.0.1 (released in March 2026), doesn't contain the package “pkg_resources” anymore. This package is used in Atlite, which is why it generates this error.
I had to install/downgrade to version 81.0.0.